- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present
- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "https://github.com/joseph-lozano/dotfiles.git"
    dest: "/home/{{ username }}/.dotfiles"
    force: yes  # Use force to discard any local changes in the repository directory
  become: yes  # Run as root
  become_user: "{{ username }}"  # Switch to the user account

- name: Clone Powerlevel10k theme for Oh My Zsh
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1  # This creates a shallow clone with only the latest snapshot
  become: yes
  become_user: "{{ username }}"

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "/home/{{ username }}/.zshrc"
  register: zshrc_stat

- name: Backup existing .zshrc if it exists
  ansible.builtin.command:
    cmd: mv "/home/{{ username }}/.zshrc" "/home/{{ username }}/.zshrc.backup"
  when: zshrc_stat.stat.exists

- name: Create symlink for .zshrc
  ansible.builtin.file:
    src: "/home/{{ username }}/.dotfiles/.zshrc"
    dest: "/home/{{ username }}/.zshrc"
    state: link
    
- name: Check if .config exists
  ansible.builtin.stat:
    path: "/home/{{ username }}/.config"
  register: config_stat

- name: Backup existing .config if it exists
  ansible.builtin.command:
    cmd: mv "/home/{{ username }}/.config" "/home/{{ username }}/.config.backup"
  when: config.stat.exists

- name: Create symlink for .config
  ansible.builtin.file:
    src: "/home/{{ username }}/.dotfiles/.config"
    dest: "/home/{{ username }}/.config"
    state: link

- name: Check if .gitconfig exists
  ansible.builtin.stat:
    path: "/home/{{ username }}/.gitconfig"
  register: gitconfig_stat

- name: Backup existing .gitconfig if it exists
  ansible.builtin.command:
    cmd: mv "/home/{{ username }}/.gitconfig" "/home/{{ username }}/.gitconfig.backup"
  when: gitconfig_stat.stat.exists

- name: Create symlink for .gitconfig
  ansible.builtin.file:
    src: "/home/{{ username }}/.dotfiles/.gitconfig"
    dest: "/home/{{ username }}/.gitconfig"
    state: link

- name: Check if .p10k.zsh exists
  ansible.builtin.stat:
    path: "/home/{{ username }}/.p10k.zsh"
  register: p10k_stat

- name: Backup existing .p10k.zsh if it exists
  ansible.builtin.command:
    cmd: mv "/home/{{ username }}/.p10k.zsh" "/home/{{ username }}/.p10k.zsh.backup"
  when: p10k_stat.stat.exists

- name: Create symlink for .p10k.zsh
  ansible.builtin.file:
    src: "/home/{{ username }}/.dotfiles/.p10k.zsh"
    dest: "/home/{{ username }}/.p10k.zsh"
    state: link
    
